baseURL = 'https://anhack.xyz/'
title = 'anhack blog'
theme = 'asperity'
languageCode = 'en-US'
defaultContentLanguage = 'en'
copyright = 'alexander hack, 2024'
keywords = 'blog,developer,development,personal'
enableRobotsTXT = true
summaryLength = 50
pagination.pagerSize = 8
enableGitInfo = true

[taxonomies]
	category = 'category'
	tag = 'tags'

[params]
	source = 'https://github.com/signet-marigold/anhack.xyz'
	licenceText = 'Licensed under CC-BY 4.0'
	licenceLink = 'https://creativecommons.org/licenses/by/4.0/'
	analyticsText = 'Uses Umami Analytics'
	analyticsLink = 'https://data-sb-v-analytics.anhack.com/share/3SKpsTgESfggNkdM/anhack'
	showbadges = true
	summaryMaxChar = 200
	tocMinWordCount = 480
	[params.author]
		name = 'alex'
		email = 'me@anhack.xyz'

[sitemap]
	changeFreq = 'weekly'
	filename = 'msitemap.xml'
	priority = -1

[menu]
	[[menu.main]]
		identifier = 'about'
		name = 'About'
		url = '/about/'
		weight = 10

	[[menu.main]]
		identifier = 'posts'
		name = 'Posts'
		url = '/posts/'
		weight = 20

	[[menu.main]]
		identifier = 'projects'
		name = 'Projects'
		url = '/projects/'
		weight = 30

	[[menu.main]]
		identifier = 'tags'
		name = 'Tags'
		url = '/tags/'
		weight = 40

	[[menu.main]]
		identifier = 'category'
		name = 'Categories'
		url = '/category/'
		weight = 50

	[[menu.main]]
		identifier = 'playlist'
		name = 'Playlist'
		url = '/playlist/'
		weight = 90

[imaging]
	[imaging.exif]
		disableDate = true
		disableLatLong = true

[markup]
	defaultMarkdownHandler = 'goldmark'
	[markup.tableOfContents]
		startLevel = 1
		endLevel = 4
		ordered = false
	[markup.highlight]
		style = 'monokai'
		tabWidth = 4
	[markup.goldmark]
		[markup.goldmark.parser]
			[markup.goldmark.parser.attribute]
				block = true

