baseURL = 'https://anhack.xyz/'
title = 'anhack'
theme = 'asperity'
languageCode = 'en'
defaultContentLanguage = 'en'
copyright = '&copy; 2023 Alexander Hack. All Right Reserved.'
keywords = 'blog,developer,personal'
enableRobotsTXT = true
summaryLength = 50


[taxonomies]
	category = 'category'
	tag = 'tags'

[params]
	showbadges = true
	summaryMaxChar = 300

[sitemap]
	changeFreq = 'weekly'
	filename = 'sitemap.xml'
	priority = -1

[menu]
	[[menu.main]]
		identifier = 'about'
		name = 'About'
		url = '/about/'
		weight = 10

	[[menu.main]]
		identifier = 'posts'
		name = 'Posts'
		url = '/posts/'
		weight = 20

	[[menu.main]]
		identifier = 'projects'
		name = 'Projects'
		url = '/projects/'
		weight = 30

	[[menu.main]]
		identifier = 'tags'
		name = 'Tags'
		url = '/tags/'
		weight = 40

	[[menu.main]]
		identifier = 'category'
		name = 'Categories'
		url = '/category/'
		weight = 50

	[[menu.main]]
		identifier = 'github'
		name = 'Github'
		url = 'https://github.com/signet-marigold/'
		weight = 900
