#!/bin/sh

[ ! -f .env ] || export $(grep -v '^#' .env | xargs)

BUILD_FLAGS=--minify

# clean build
rm -rf public/*
hugo ${BUILD_FLAGS} && sshpass -p ${DHOUS_PASS} rsync -avz --delete public/ ${DHOUS_USER}@${DHOUS_HOST}:~/${DHOUS_DIR}

exit 0
