title = 'Fignat'
languageCode = 'en-us'

[params]
	showHomeTitle = false
	homeTitle = ''
	homeSubtitle = ''
	
	nextPrev = true
	tagList = true
	showLicence = true
	showAnalytics = true
	showCopyright = true
	showLastBuild = true
	showThemeInfo = true
	showSource = true
	showRSS = true
	showThemeToggle = true

	# Don't know where this one is
	commit = false

	# Post preview and meta settings
	summary = true
	readingTime = true
	wordCount = false
	showRelatedPosts = true
	hideAuthor = true
	hideTags = false
	showPreviewImage = false
	showPreviewVideo = false
	showPreviewSummary = true
	
	switchSiteURL = 'https://anhack.xyz'
