name = 'Fignat'
license = 'MIT'
licenselink = 'https://github.com/signet-marigold/anhack.xyz/blob/main/themes/fignat/LICENSE'
description = ''
tags = ['blog', 'projects', 'mobile']
features = ['blog', 'projects', 'mobile']
min_version = 0.132

[author]
    name = 'anhack'
    email = 'me@anhack.xyz'
    homepage = 'https://anhack.xyz'
