baseURL = 'https://simple.anhack.xyz/'
theme = 'fignat'
publishDir = 'public-simple'

[[module.mounts]]
source = 'content'
target = 'content'

[[module.mounts]]
source = 'content-simple'
target = 'content'

[params]
	logoPathDefault = '/img/logo-simplep.png'
	logoPathAlt     = '/img/logo-light-simplep.png'

disableKinds = ['sitemap', 'rss']

[sitemap]
	disable = true

[outputs]
	home = ['html']
	section = ['html']
	taxonomy = ['html']
	term = ['html']

[menu]
	[[menu.main]]
		identifier = 'home'
		name = 'Home'
		url = '/'
		weight = 10

	[[menu.main]]
		identifier = 'about'
		name = 'About'
		url = '/about/'
		weight = 20

	[[menu.main]]
		identifier = 'posts'
		name = 'Posts'
		url = '/posts/'
		weight = 30

	[[menu.main]]
		identifier = 'projects'
		name = 'Projects'
		url = '/projects/'
		weight = 40

	[[menu.main]]
		identifier = 'tags'
		name = 'Tags'
		url = '/tags/'
		weight = 50

	[[menu.main]]
		identifier = 'category'
		name = 'Categories'
		url = '/category/'
		weight = 60

	[[menu.main]]
		identifier = 'simplified'
		name = 'Simplified?'
		url = '/what-is-simplified/'
		weight = 70
