title = 'Asperty'
languageCode = 'en-us'

[params]
	# List items
	datesinlist = true
	authorsinlist = true

	# Footer items
	nextprev = true
	taglist = true
	showrss = true
	showthemeinfo = false

	# Don't know where this one is
	commit = false

	# Post preview and meta settings
	summary = true
	readingTime = true
	wordCount = false
	showRelatedPosts = true
	hideAuthor = false
	hideTags = false
	showPreviewImage = false
	showPreviewVideo = false
	showPreviewSummary = false

	# Table of Contents
	tocMinWordCount = 480
