title = 'Asperty'
languageCode = 'en-us'

[params]
	# 'relatedtext' is the text that appears above the tag list at the bottom of pages.
	#relatedtext = 'Related'

	#dateFormat = "Jan 2, 2006"

	#list items
	datesinlist = true
	authorsinlist = true

	#footer items
	nextprev = true
	taglist = true
	showrss = true
	showthemeinfo = false
	commit = false
	summary = true
	readingTime = true
	wordCount = false
	showRelatedPosts = true
	hideAuthor = false
	hideTags = false
	showPreviewImage = false
	showPreviewVideo = false
	showPreviewSummary = false

[imaging]
  [imaging.exif]
    disableDate = true
    disableLatLong = true

