title = 'Asperty'
languageCode = 'en-us'

[params]
	# List items
	datesinlist = true
	authorsinlist = true

	# Footer items
	nextPrev = true
	tagList = true
	showLicence = true
	showAnalytics = true
	showCopyright = true
	showLastBuild = true
	showThemeInfo = true
	showSource = true
	showRSS = true
	showThemeToggle = true

	# Don't know where this one is
	commit = false

	# Post preview and meta settings
	summary = true
	readingTime = true
	wordCount = false
	showRelatedPosts = true
	hideAuthor = false
	hideTags = false
	showPreviewImage = true
	showPreviewVideo = false
	showPreviewSummary = true

	# Table of Contents
	tocMinWordCount = 480
