title = 'Asperty'
languageCode = 'en-us'

[params]
	logoPathDefault = '/img/logo.png'
	logoPathAlt     = '/img/logo-light.png'

	showHomeTitle = false
	homeTitle = ''
	homeSubtitle = ''

	# List items
	datesinlist = true
	authorsinlist = true

	# Footer items
	nextPrev = true
	returnTopic = true
	tagList = true
	showLicence = true
	showAnalytics = true
	showCopyright = true
	showLastBuild = true
	showThemeInfo = true
	showSource = true
	showRSS = true
	showThemeToggle = true

	# Post preview and meta settings
	summary = true
	readingTime = true
	wordCount = false
	showRelatedPosts = true
	hideAuthor = true
	hideTags = false
	showPreviewImage = true
	showPreviewVideo = false
	showPreviewSummary = true

	# Table of Contents
	tocMinWordCount = 480
	
	switchSiteURL = 'https://simple.anhack.xyz'

[menu]
	[[menu.main]]
		identifier = 'home'
		name = 'Home'
		url = '/'
		weight = 10
