title = 'Asperty'
languageCode = 'en-us'

[params]
	# 'relatedtext' is the text that appears above the tag list at the bottom of pages.
	relatedtext = 'Related'
	logo = '/logo.png'
	favicon = '/favicon.ico'

	#list items
	datesinlist = true
	authorsinlist = true

	#footer items
	nextprev = true
	taglist = true
	showrss = true
	showthemeinfo = false
	dateFormat = "Jan 2, 2006"
	commit = false
	summary = true
	readingTime = true
	wordCount = false
	showRelatedPosts = true
	hideAuthor = false
	hideTags = false
	showPreviewImage = false
	showPreviewVideo = false
	showPreviewSummary = false
